### ISSUE TITLE
La dernière PR

### ISSUE THREAD

**Issue by Alvai** [g123k/supinternet-aqi#9]
Bonsoir Edouard,

La CI  à mit trop de temps à passer, On à pas eu le temps de merge la dernière PR, Est-ce que c'est toi qui à  bloquer les merges ?
Louis à travailler dur sur la dernière PR, on veux juste la merger
on attendais la CI.

**Comment by g123k** [comment]
Je viens de te donner les droits pour que tu puisses valider
BTW c'était 19h10 quand j'ai enlevé les droits ;)

**Comment by Alvai** [comment]
![image](https://user-images.githubusercontent.com/32277602/69885603-42bddc00-12de-11ea-8a7e-02e93d067348.png)
Je peux pas merge 😢

**Comment by LouisLoiseau** [comment]
Bonsoir,

La ci de la pr a bien finit à 19h11. https://app.bitrise.io/build/5c75126b41f635c3#?tab=log

Bonne soirée,

Louis Loiseau-Billon.

**Comment by Alvai** [comment]
LA PR EST MERGER

MERCI EDOUARD,
BONNE SOIREE

**Comment by g123k** [comment]
Merci à tous, bon week-end.
